version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb/Dockerfile
    volumes: 
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "9000:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - backend
      - frontend

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/Dockerfile
    ports: 
      - "80:80"
    networks:
      - frontend

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
